bugfix: Including default "finally" hook. This fulfills required property in type HooksObject.
* Tested on CLI Plus Version: 0.8.10
* See my feathers-gen-specs.json below if needed.
* The error occurs when running `yarn start` immediately after `feathers-plus generate app`.

**Excerpt of error message:**

```
yarn run v1.13.0
$ ts-node --files src/

/Volumes/dev/camera-challenge-fjs/node_modules/ts-node/src/index.ts:261
    return new TSError(diagnosticText, diagnosticCodes)
           ^
TSError: ⨯ Unable to compile TypeScript:
src/app.hooks.ts(15,5): error TS2741: Property 'finally' is missing in type '{ before: { all: Hook[]; find: never[]; get: never[]; create: never[]; update: never[]; patch: never[]; remove: never[]; }; after: { all: Hook[]; find: never[]; get: never[]; create: never[]; update: never[]; patch: never[]; remove: never[]; }; error: { ...; }; }' but required in type 'HooksObject'.
```

**My feathers-gen-specs.json**

```
{
  "options": {
    "ver": "1.0.0",
    "inspectConflicts": false,
    "semicolons": true,
    "freeze": [],
    "ts": true
  },
  "app": {
    "environmentsAllowingSeedData": "",
    "seedData": false,
    "name": "camera-challenge-fjs",
    "description": "Project camera-challenge-fjs",
    "src": "src",
    "packager": "yarn@>= 0.18.0",
    "providers": [
      "rest",
      "socketio"
    ]
  },
  "services": {},
  "hooks": {}
}
```